# Generated by Django 5.0 on 2023-12-11 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='Recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Recipe_app.list'),
        ),
    ]
