# Generated by Django 5.0 on 2023-12-25 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe_app', '0006_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
