# Generated by Django 5.0 on 2023-12-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe_app', '0007_delete_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(upload_to='getFileName'),
        ),
    ]
