# Generated by Django 5.0 on 2023-12-27 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe_app', '0010_save_savedrecipe_delete_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='save',
            name='image',
        ),
        migrations.RemoveField(
            model_name='save',
            name='name',
        ),
    ]
