# Generated by Django 5.0 on 2023-12-27 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe_app', '0011_remove_save_image_remove_save_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedrecipe',
            name='Recipes',
        ),
        migrations.AddField(
            model_name='savedrecipe',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Recipe_app.recipes'),
        ),
    ]
