# Generated by Django 5.0 on 2023-12-28 11:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe_app', '0013_userfeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedrecipe',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='savedrecipe',
            name='user',
        ),
        migrations.AddField(
            model_name='recipes',
            name='saved_by',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Save',
        ),
        migrations.DeleteModel(
            name='Savedrecipe',
        ),
    ]
